Repository 0xProject/0x-launch-kit-frontend, pull requests merged in 2019-05, with the labels that each got.

#404 (Feature) Fixs progress bar fully-filed even if the transaction is not finished
  src/tests/util/steps.test.ts
  src/util/steps.ts
Labels: 0x feedback

#406 (Feature) Fix my size light dash
  src/components/erc20/marketplace/order_book.tsx
Labels: 0x feedback

#408 (Feature) Steps modals delays
  .env.example
  src/common/constants.ts
  src/components/common/steps_modal/steps_common.tsx
  src/components/common/steps_modal/toggle_token_lock_step.tsx
  src/components/common/steps_modal/unlock_collectibles_step.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
Labels: 0x feedback

#414 (Feature) HashRouter
  src/components/erc20/common/markets_dropdown.tsx
  src/store/index.ts
Labels: 0x feedback

#410 (Feature) Percentage Spread
  src/common/constants.ts
  src/components/erc20/marketplace/order_book.tsx
  src/store/selectors.ts
  src/tests/components/erc20/marketplace/order_book.test.tsx
  src/tests/store/selectors.test.ts
  src/util/types.ts
Labels: 0x feedback

#439 (Feature) Display more decimals in convert weth modal
  src/components/account/wallet_weth_modal.tsx
  src/components/common/big_number_input.tsx
Labels: 0x feedback

#440 (Feature) Adds bold text to wethTotal
  src/components/account/wallet_token_balances.tsx
  src/tests/components/account/__snapshots__/wallet_token_balances.test.tsx.snap
Labels: 0x feedback

#426 (Feature) ERC20 Default theme as dark
  .env.example
  THEMES.md
  src/common/constants.ts
  src/components/erc20/erc20_app.tsx
  src/components/erc721/erc721_app.tsx
  src/components/general_layout.tsx
  src/index.tsx
  src/store/selectors.ts
  src/store/ui/actions.ts
  src/store/ui/reducers.ts
  src/themes/default_theme.ts
  src/themes/theme_meta_data.ts
  src/themes/theme_meta_data_utils.ts
  src/util/types.ts
Labels: 0x feedback

#438 (Feature) Adds a warning card if the user is not on an available network
  src/components/common/error_card.tsx
  src/components/common/icons/warning_icon.tsx
  src/components/common/toolbar.tsx
  src/components/erc20/marketplace/wallet_balance.tsx
  src/tests/components/common/__snapshots__/toolbar.test.tsx.snap
  src/util/error_messages.ts
Labels: 0x feedback

#449 (Feature) Buy sell flow modal improvements
  src/common/constants.ts
  src/components/account/wallet_weth_modal.tsx
  src/components/common/icons/icon_metamask_large.tsx
  src/components/common/steps_modal/base_step_modal.tsx
  src/components/common/steps_modal/steps_common.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
Labels: 0x feedback

#447 Buy/Sell panel colors
  src/components/account/wallet_weth_modal.tsx
  src/components/common/button.tsx
  src/components/common/metamask_error_modal.tsx
  src/components/erc20/marketplace/buy_sell.tsx
  src/components/erc20/marketplace/order_book.tsx
  src/components/erc20/marketplace/order_history.tsx
  src/components/erc20/marketplace/wallet_balance.tsx
  src/components/erc721/collectibles/collectible_sell_modal.tsx
  src/components/erc721/marketplace/sell_collectibles_button.tsx
  src/components/erc721/marketplace/trade_button.tsx
  src/themes/commons.ts
  src/themes/dark_theme.ts
  src/themes/default_theme.ts
  src/util/types.ts
Labels: 0x feedback

#450 (Feature) Enhance error messages on buy sell
  src/components/common/steps_modal/sign_order_step.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
  src/components/erc20/marketplace/buy_sell.tsx
  src/exceptions/common.tsx
  src/exceptions/insufficient_eth_deposit_balance_exception.ts
  src/exceptions/insufficient_fee_balance_exception.ts
  src/exceptions/insufficient_orders_amount_exception.ts
  src/exceptions/insufficient_token_balance_exception.ts
  src/exceptions/relayer_exception.ts
  src/store/relayer/actions.ts
  src/store/selectors.ts
  src/store/ui/actions.ts
Labels: 0x feedback

#493 Add rate limiting for opensea and relayer
  package.json
  src/services/collectibles_metadata_sources/index.ts
  src/services/collectibles_metadata_sources/opensea.ts
  src/services/relayer.ts
  src/store/relayer/actions.ts
  yarn.lock
Labels: high priority

#473 (Feature) Split store update between apps
  src/store/actions.ts
  src/store/blockchain/actions.ts
  src/store/selectors.ts
Labels: high priority

#501 Don't update store's relayer state on get orders errors.
  src/services/orders.ts
  src/store/relayer/actions.ts
Labels: bug, high priority

#502 Redirect to asset page after item is placed on sale
  src/components/common/steps_modal/buy_sell_collectible_step.tsx
  src/components/common/steps_modal/steps_modal.tsx
  src/store/router/actions.ts
Labels: 0x feedback, medium priority

#500 (Feature) Close dropdown on click outside
  src/components/account/wallet_connection_status.tsx
  src/components/account/wallet_weth_balance.tsx
  src/components/common/dropdown.tsx
  src/components/erc20/account/wallet_connection_content.tsx
  src/components/erc20/common/markets_dropdown.tsx
  src/components/erc721/account/wallet_connection_content.tsx
  src/components/notifications/notifications_dropdown.tsx
Labels: 0x feedback, medium priority
