Repository 0xProject/0x-launch-kit-frontend, pull requests merged in 2019-06, with the labels that each got.

#512 Add ThemeProperties.cardImageBackgroundColor.
  src/components/erc721/collectibles/collectible_card.tsx
  src/themes/commons.ts
  src/themes/dark_theme.ts
  src/themes/default_theme.ts
Labels: 0x feedback, medium priority

#511 (Hotfix) Fixes the balances check on market operation
  src/store/ui/actions.ts
Labels: 0x feedback, bug

#519 Hotfix/disable update balance button
  src/components/account/wallet_weth_modal.tsx
Labels: bug, low priority

#525 Estimate wait times are too long
  src/common/constants.ts
  src/services/gas_price_estimation.ts
Labels: 0x feedback

#527 Orderbook doesn't show orders until wallet connects to Mainet
  src/services/orders.ts
  src/store/relayer/actions.ts
Labels: 0x feedback

#528 Show proper message when user rejects/cancel ETH wrapping
  src/components/common/steps_modal/base_step_modal.tsx
  src/components/common/steps_modal/sign_order_step.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
  src/exceptions/common.ts
  src/exceptions/component_unmounted_exception.ts
  src/exceptions/signature_failed_exception.ts
  src/exceptions/user_denied_transaction_exception.ts
Labels: 0x feedback

#531 Show your own NFT in “for sale” view
  src/components/erc721/collectibles/collectible_card.tsx
  src/components/erc721/collectibles/collectibles_all.tsx
  src/components/erc721/collectibles/collectibles_card_list.tsx
  src/components/erc721/collectibles/collectibles_list.tsx
  src/components/erc721/collectibles/owner_badge.tsx
  src/store/selectors.ts
  src/tests/components/erc721/collectibles/__snapshots__/owner_badge.test.tsx.snap
  src/tests/components/erc721/collectibles/owner_badge.test.tsx
  src/themes/commons.ts
  src/themes/dark_theme.ts
  src/themes/default_theme.ts
Labels: 0x feedback, Critical

#533 Setup default network
  .env.example
  src/common/constants.ts
  src/common/tokens_meta_data.ts
  src/components/account/wallet_weth_modal.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
  src/components/common/tooltip.tsx
  src/components/erc20/marketplace/order_details.tsx
  src/components/erc721/collectibles/collectibles_card_list.tsx
  src/components/notifications/notification_item.tsx
  src/components/notifications/notifications_dropdown.tsx
  src/services/collectibles_metadata_gateway.ts
  src/services/collectibles_metadata_sources/mocked.ts
  src/services/collectibles_metadata_sources/opensea.ts
  src/services/contract_wrappers.ts
  src/services/local_storage.ts
  src/services/markets.ts
  src/services/tokens.ts
  src/store/actions.ts
  src/store/blockchain/actions.ts
  src/store/blockchain/reducers.ts
  src/store/collectibles/actions.ts
  src/store/market/actions.ts
  src/store/middlewares.ts
  src/store/selectors.ts
  src/tests/services/collectibles_metadata_gateways.test.ts
  src/tests/util/known_tokens.test.ts
  src/tests/util/notifications.test.ts
  src/util/error_messages.ts
  src/util/known_tokens.ts
  src/util/notifications.ts
  src/util/token_meta_data.ts
  src/util/transaction_link.ts
  src/util/types.ts
Labels: 0x feedback, Critical, in progress

#534 Frontend supports only 18 decimal tokens
  src/components/erc20/marketplace/buy_sell.tsx
  src/components/erc20/marketplace/wallet_balance.tsx
  src/services/relayer.ts
  src/tests/util/orders.test.ts
  src/tests/util/ui_orders.test.ts
  src/util/known_tokens.ts
  src/util/orders.ts
  src/util/ui_orders.ts
Labels: 0x feedback, Critical

#536 Some minor improvements related to network detection
  src/services/collectibles_metadata_gateway.ts
  src/store/blockchain/actions.ts
  src/store/relayer/actions.ts
  src/store/selectors.ts
Labels: 0x feedback, Critical

#539 Fill in limit order price when clicking on orderbook
  src/components/common/show_number_with_colors.tsx
  src/components/erc20/marketplace/buy_sell.tsx
  src/components/erc20/marketplace/order_book.tsx
  src/store/selectors.ts
  src/store/ui/actions.ts
  src/store/ui/reducers.ts
  src/tests/components/erc20/marketplace/__snapshots__/order_book.test.tsx.snap
  src/tests/components/erc20/marketplace/order_book.test.tsx
  src/themes/commons.ts
  src/themes/dark_theme.ts
  src/themes/default_theme.ts
  src/util/types.ts
Labels: 0x feedback, high priority

#541 Broken dropdown If one token is not supported by the backend
  src/store/market/actions.ts
  src/util/known_tokens.ts
Labels: bug, medium priority

#546 Improvements in the conversion from eth to weth
  package.json
  src/components/account/wallet_weth_modal.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
  src/exceptions/convert_balance_must_not_be_equal_exception.ts
  src/store/actions.ts
  src/store/blockchain/actions.ts
  src/util/transactions.ts
  yarn.lock
Labels: 0x feedback, Critical

#547 Disable conversion button while the transaction is running
  src/components/account/wallet_weth_balance.tsx
  src/components/common/steps_modal/wrap_eth_step.tsx
  src/store/blockchain/actions.ts
  src/store/blockchain/reducers.ts
  src/store/selectors.ts
  src/util/types.ts
Labels: 0x feedback, Critical

#549 Use forwarder on market buys when wETH is the quote token.
  src/store/relayer/actions.ts
  src/store/ui/actions.ts
  src/tests/util/steps_modals_generation.test.ts
  src/util/steps_modals_generation.ts
Labels: 0x feedback, Critical
